### ISSUE TITLE
カーソル/グランマを購入しようとしたとき、NullReferenceExceptionが出力される。

### ISSUE THREAD

**Issue by AoiTomiyama** [VGA-GLAB/2024_Clicker_A#11]
ResourceManagerに未割り当てのTMProがあるので、修正お願いします。

**Comment by Kasahara-Sota** [comment]
八木君いなくなっちゃったから代わりに修正します

**Comment by AoiTomiyama** [comment]
https://github.com/VGA-GLAB/2024_Clicker_A/pull/12
で不具合の修正確認できたのでClosesします。
